### ISSUE TITLE
Latest Version Functionality Not Working and "Download Failed" Message Not Thrown

### ISSUE THREAD

**Issue by PeterParker** [hamnis/maven-artifact#1]
Downloading the following _particular version_ of an artifact works fine:

```
maven-artifact --maven-repo="https://www.icatproject.org/mvn/repo" "org.icatproject:icat.server:zip:distro:4.7.0"
```

However, when I try to download the _latest_ version ...

```
maven-artifact --maven-repo="https://www.icatproject.org/mvn/repo" "org.icatproject:icat.server:zip:distro:latest"
```

... I get:

```
Traceback (most recent call last):
  File "/Users/.../anaconda3/envs/py27/bin/maven-artifact", line 11, in <module>
    sys.exit(main())
  File "/Users/.../anaconda3/envs/py27/lib/python2.7/site-packages/maven/downloader.py", line 146, in main
    if dl.download(artifact, filename):
  File "/Users/.../anaconda3/envs/py27/lib/python2.7/site-packages/maven/downloader.py", line 18, in download
    if not self.verify_md5(filename, url + ".md5"):
  File "/Users/.../anaconda3/envs/py27/lib/python2.7/site-packages/maven/downloader.py", line 80, in verify_md5
    remote = self.requestor.request(remote_md5, onError, lambda r: r.read())
  File "/Users/.../anaconda3/envs/py27/lib/python2.7/site-packages/maven/requestor.py", line 19, in request
    onFail(url, e)
  File "/Users/.../anaconda3/envs/py27/lib/python2.7/site-packages/maven/downloader.py", line 79, in <lambda>
    onError = lambda uri, err: _throwDownloadFailed("Failed to download MD5 from " + uri)
NameError: global name '_throwDownloadFailed' is not defined
```

**EDIT** - I see a similar functionality when I try to download a _snapshot_ version:

```
maven-artifact --maven-repo="https://www.icatproject.org/mvn/repo" "org.icatproject:icat.server:zip:distro:4.7.0-SNAPSHOT"
```

**Comment by PeterParker** [comment]
By the way, this is a very nice module as far as I can tell.  Using it means I do not have to download Maven in its entirety (and the up-to-date versions of all it's plugins/dependencies..) just to download a few  zip files from a Maven repository as part of a Python project deployed to a Docker container.

**Comment by hamnis** [comment]
Hello.

Thanks for the report.
